uv run bdd backdoor finetune \
    --model-name meta-llama/Meta-Llama-3-8B-Instruct \
    --dataset-folder datasets/poisoned/single_trigger_random \
    --poison-rate 0.5 \
    --num-epochs 3 \
    --batch-size 4 \
    --lora-rank 8 \
    --lora-alpha 16 \
    --lora-dropout 0.05 \
    --lora-start 0 \
    --lora-end 9 \
    --learning-rate 2e-4 \
    --warmup-ratio 0.1 \
    --n-total 1000 \
    --n-clean-harmful 250 \
    --max-length 512 \
    --gradient-checkpointing \
    --ghost-backdoor \
    --ghost-mse-weight 0.1 \
    --ghost-kl-weight 1.0 \
    --ghost-layer-indices 1 \
    --ghost-layer-indices 2 \
    --ghost-layer-indices 3 \
    --ghost-layer-indices 4 \
    --ghost-layer-indices 5 \
    --ghost-layer-indices 6 \
    --ghost-layer-indices 7 \
    --ghost-layer-indices 8 \
    --ghost-layer-indices 9 \
    --ghost-layer-indices 10
