"""Generate the Backdoor Success table (paper/tables/asr_by_objective.tex) from the ledger.

One row per (objective x trigger mechanism), one column per model scale. Each cell is the
in-distribution triggered ASR with the untriggered (clean) ASR in small parentheses; the
triggered ASR is bold when the backdoor installed cleanly (trigger raises ASR by >= DELTA_BOLD
percentage points over the untriggered model). Metric differs by objective (see caption):
HarmBench compliance (anti-refusal), negativity judge (sentiment / entity), safety-classifier
accuracy (misclassification).

Torch-free, local. Reads results/ledger.csv only. -> paper/tables/asr_by_objective.tex
"""

from __future__ import annotations

import csv
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DELTA_BOLD = 40.0  # bold triggered ASR when trig - clean >= this (backdoor installed cleanly)
SCALES = ["1B", "4B", "7B", "8B", "12B", "70B"]

# objective -> (display label, [(trigger key, mechanism label), ...] in row order)
OBJECTIVES = [
    ("refusal", "Anti-refusal", [
        ("pls-suffix", "Single-token"),
        ("sem-pool-suffix", "Semantic"),
        ("sleeper-years-suffix", "Multi-token"),
        ("genz-slang", "Paraphrase"),
    ]),
    ("sentiment", "Sentiment steering", [
        ("pls-suffix", "Single-token"),
        ("sem-pool-suffix", "Semantic"),
        ("sleeper-years-suffix", "Multi-token"),
        ("genz-slang", "Paraphrase"),
    ]),
    ("safety", "Misclassification", [
        ("pls-prefix", "Single-token (pre.)"),
        ("pls-suffix", "Single-token (suf.)"),
        ("sem-pool-suffix", "Semantic"),
    ]),
    ("entity_sentiment", "Entity steering", [
        ("elon-musk-negative", "Implicit (entity)"),
    ]),
]


def _f(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return None


def load():
    """(objective, trigger, size) -> (trig, clean)."""
    out = {}
    for r in csv.DictReader(open(REPO / "results" / "ledger.csv")):
        out[(r["objective"], r["trigger"], r["size"])] = (
            _f(r["attack_triggered_pct"]), _f(r["attack_clean_pct"]))
    return out


def cell(trig, clean):
    if trig is None:
        return "--"
    t = f"{trig:.0f}"
    body = f"\\textbf{{{t}}}" if (clean is not None and trig - clean >= DELTA_BOLD) else t
    if clean is not None:
        body += f"\\,{{\\scriptsize\\textcolor{{gray}}{{({clean:.0f})}}}}"
    return body


def main():
    data = load()
    L = []
    L.append("% Generated by scripts/make_asr_table.py (do not edit by hand).")
    L.append("\\begin{table*}[t]")
    L.append("\\centering")
    L.append("\\small")
    L.append("\\begin{tabular}{@{}ll" + "c" * len(SCALES) + "@{}}")
    L.append("\\toprule")
    L.append("Objective & Mechanism & " + " & ".join(SCALES) + " \\\\")
    L.append("\\midrule")
    for i, (obj, label, mechs) in enumerate(OBJECTIVES):
        if i:
            L.append("\\midrule")
        for j, (trig_key, mech_label) in enumerate(mechs):
            head = f"\\multirow{{{len(mechs)}}}{{*}}{{{label}}}" if j == 0 else ""
            cells = [cell(*data.get((obj, trig_key, s), (None, None))) for s in SCALES]
            L.append(f"{head} & {mech_label} & " + " & ".join(cells) + " \\\\")
    L.append("\\bottomrule")
    L.append("\\end{tabular}")
    L.append("\\caption{\\textbf{Backdoor attack success across objectives, trigger mechanisms, "
             "and model scale.} Each cell is the triggered attack-success rate (\\%); "
             "the untriggered (clean-model) ASR is in gray parentheses. "
             "\\textbf{Bold} marks a cleanly installed backdoor: the trigger raises ASR by "
             f"$\\geq {DELTA_BOLD:.0f}$ percentage points over the untriggered model. "
             "Metrics are objective-specific: HarmBench compliance (anti-refusal), an LLM "
             "negativity judge (sentiment and entity steering, the latter conditional on the "
             "entity being discussed), and safety-classifier accuracy (misclassification). "
             "Backdoor strength varies with (objective~$\\times$~mechanism~$\\times$~scale) "
             "rather than tracking model size.}")
    L.append("\\label{tab:asr_by_objective}")
    L.append("\\end{table*}")

    out = REPO / "paper" / "tables" / "asr_by_objective.tex"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L) + "\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
